# ============================================
# STEP 2: Secrets Configuration
# ============================================
# PURPOSE: Stores sensitive data like passwords and API keys securely
# WHY: Secrets are base64 encoded and can be mounted as environment variables
#      or files. They keep sensitive data out of your deployment configs.
# SECURITY: Never commit real secrets to Git! Use placeholder values and
#           update them manually in OpenShift, or use sealed-secrets.
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: event-scheduling-db-secret
  namespace: event-scheduling
  labels:
    app: event-scheduling
    component: database
type: Opaque
stringData:
  # PostgreSQL superuser credentials
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: event_scheduling_db
  # Application database user credentials
  DB_USER: auth_user
  DB_PASSWORD: "mohamed2004###"
  # JWT secret for token signing
  JWT_SECRET: "Secret_Key_2025_FCAI_CU_SWE_RedHat_Tools_OpenShift"
